# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('marketing', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=255)),
                ('completed_by', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=10)),
                ('checked_by', models.CharField(max_length=5)),
                ('set_up_by', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='supportquestions',
            name='support_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SupportSurvey'),
        ),
    ]
