# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='launchQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('marketing', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('advisor', models.CharField(max_length=255)),
                ('sales', models.CharField(max_length=255)),
                ('ordered', models.DateField()),
                ('launched', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='launchquestions',
            name='launch_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.LaunchSurvey'),
        ),
    ]
