# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_supportsurvey_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportquestions',
            name='id',
        ),
        migrations.AlterField(
            model_name='supportquestions',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportquestions',
            name='support_survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='survey.SupportSurvey'),
        ),
    ]
